version: '2'
services:
  postgresql-service:
    image: postgres:9.6.2
    container_name: "postgresql-service"
    ports:
      - "5432:5432"
  configuration-service:
    image: configuration-service:0.0.1-SNAPSHOT
    container_name: "configuration-service"
    ports:
      - "8888:8888"
