version: '2'
services:
  registry-service:
    image: registry-service:0.0.1-SNAPSHOT
    container_name: "registry-service"
    environment:
      - CONFIG_SERVER_URL=http://configuration-service:8888
      - CONFIG_EUREKA_URL=http://registry-service:8761
    ports:
      - "8761:8761"
  routing-service:
    image: routing-service:0.0.1-SNAPSHOT
    container_name: "routing-service"
    environment:
      - CONFIG_SERVER_URL=http://configuration-service:8888
      - CONFIG_EUREKA_URL=http://registry-service:8761
    ports:
      - "8082:8082"
  wallet-service:
    image: wallet-service:0.0.1-SNAPSHOT
    container_name: "wallet-service"
    environment:
      - CONFIG_SERVER_URL=http://configuration-service:8888
      - CONFIG_POSTGRESQL_URL=jdbc:postgresql://postgresql-service/postgres
      - CONFIG_EUREKA_URL=http://registry-service:8761
    ports:
      - "8090:8090"
  loyalty-service:
    image: loyalty-service:0.0.1-SNAPSHOT
    container_name: "loyalty-service"
    environment:
      - CONFIG_SERVER_URL=http://configuration-service:8888
      - CONFIG_EUREKA_URL=http://registry-service:8761
    ports:
      - "8095:8095"
