eureka:
  client:
    serviceUrl:
      preferIpAddress: true
      defaultZone: ${CONFIG_EUREKA_URL:http://localhost:8761}/eureka/
      useDnsForFetchingServiceUrls: false

logging:
  level:
    root: INFO
    com.poc.microservices: DEBUG

spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0